### PR TITLE
fix: escape XML entities

### PR DESCRIPTION
**Pull request by spaceone**
and prevent XML injections

### CODE REVIEW

**Comment by SpiritCroc** [comment]
Why not keep the `f"..."`-style format strings?

**Comment by spaceone** [comment]
Well, 1. I don't like to combine fstrings with function calls and 2. I need to be Python 3.5 compatible in my fork - so with %-syntax I have less things to fork.

**Comment by SpiritCroc** [comment]
Feels inconsistent to do it both ways, and I kind of prefer the f-strings style. python 3.6 seems old enough to me to require it :thinking:

**Comment by spaceone** [comment]
Changed back to `f'strings'`.

I can't use Python 3.6 yet - my telephone system has an very old OS ;-)

**Comment by SpiritCroc** [comment]
Oh, you can run this on your telephone system? I see why outdated software might be a problem then :sweat_smile: 
Thanks for updating the PR anyways!

**Pull request merged**
