### PR TITLE
refactor[carddav]: remove unused functionality

### PR DESCRIPTION
**Pull request by spaceone**
`xrange()` has been removed in Python 3.
The variable `response` is undefined.

### CODE REVIEW

**Comment by SpiritCroc** [comment]
Hm, I guess these functions are unused. So better to delete them?

**Comment by spaceone** [comment]
If it's some upstream file I would keep it and just rebase from time to time to the upstream variant.

**Comment by SpiritCroc** [comment]
Well, it's some file copied from some other project, but I didn't plan to update it with any upstream changes. Main idea was to get things done quickly, so I have something that works. So I didn't plan to touch this file unless something breaks, in which case I probably/hopefully can fix it myself without upstream help :shrug:

**Comment by spaceone** [comment]
OK, so I removed every unused functionality from that file.

**Comment by SpiritCroc** [comment]
Awesome, thank you!

**Pull request merged**
