### PR TITLE
style: fix some flake8 styling issues

### PR DESCRIPTION
**Pull request by spaceone**
cleaned up some styling issues so that the code conforms with `PEP 8` python style guide.

### CODE REVIEW

**Comment by SpiritCroc** [comment]
Yeah, `carddav.py` looks better with this (that's some file I imported and never meant to do much with it).
For the other files, not really persuaded I prefer that.
I kind of prefer the explicit checks in `convert.py`. And not really sure how `except Exception:` is better than `except:`.

**Comment by spaceone** [comment]
It's pythonic to not check for `== ''` or `!= None` or `len(foo)`- see https://www.python.org/dev/peps/pep-0008/.
Also `except:` catches every `BaseException` while `except Exception` doesn't catch important system exceptions like `SystemExit`, `KeyboardInterrupt`, etc. - it would be even better to replace `Exception` with a more concrete one but I don't know which are expected to happen.

**Comment by SpiritCroc** [comment]
ok, the exception thing makes sense.
I still consider `if len(numbers) > 0` easier readable and understandable than `if numbers`. If I do `if numbers`, my first impression would be that this was either checking a boolean, or if some value is (non-)null. Checking non-emptiness of sequences this way feels unnatural to me. I guess that's a question of taste.

**Comment by spaceone** [comment]
I don't think it's a question of taste but of being used to how Pythons good practices are.

See also: https://peps.python.org/pep-0008/#programming-recommendations
image

What if somehow `numbers` is `None` ?
`len(None)` will cause a crash then.

**Comment by SpiritCroc** [comment]
Yes, I saw that from your link.
Readability of my own projects seems more important to me than somebody else's code style suggestions :shrug: 
And if I write my code such that I know that value is not null, what's wrong with calling `len` on it?
But if it's so important to you, it's not that important to me to fight over it, so I can merge it if it makes you happy.

**Pull request merged**
